language: go
 
go:
- "1.12"
- master

env:
  - GO111MODULE=on

before_install:
 - go get github.com/urfave/cli/v2
 - go get github.com/sirupsen/logrus

# Don't email me the results of the test runs.
notifications:
  email: false