language: go
 
go:
- "1.12"
- master

before_install:
  - go get github.com/jawher/mow.cli
  - go get github.com/urfave/cli/v2
  - go get github.com/sirupsen/logrus

env:
  - GO111MODULE=on

install: true

# Don't email me the results of the test runs.
notifications:
  email: false